
#pragma once


///
// Find the templates for coordinate generation
//
// Autogenerated, do not edit.
//
//   $SCHRODINGER/run mol_generator.py templates.mae
//
// generated using templates.mae version b8f3bf40e52b4001cd70.
//


#include <vector>

class sketcherMinimizerMolecule;
namespace schrodinger {

///
// Create a new vector of sketcherMinimizerMolecule*. Caller
// owns the sketcherMinimizerMolecule objects.
std::vector<sketcherMinimizerMolecule*> coordgen_templates();

}
